# -*- coding: utf-8 -*-
"""Crowd_Management_AI_SDG11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARnTajGdTg9CG-_YRI7OmryC2MdvnkzG
"""

!nvidia-smi

!pip install -q ultralytics opencv-python matplotlib

import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

from google.colab import files
uploaded = files.upload()

img_path = list(uploaded.keys())[0]

results = model(img_path)

res = results[0].plot()

plt.figure(figsize=(10,6))
plt.imshow(res)
plt.axis('off')
plt.show()

boxes = results[0].boxes
person_count = len(boxes)

print("Total number of people detected:", person_count)

img = cv2.imread(img_path)
h, w, _ = img.shape
area = h * w

density = person_count / area

print("Crowd density:", density)

if person_count < 15:
    risk = "LOW"
    color = "green"
elif person_count < 40:
    risk = "MEDIUM"
    color = "yellow"
else:
    risk = "HIGH"
    color = "red"

print("Crowd Risk Level:", risk)

import cv2
import matplotlib.pyplot as plt

img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

for box in results[0].boxes.xyxy:
    x1, y1, x2, y2 = map(int, box)
    cv2.rectangle(img, (x1, y1), (x2, y2), (255, 0, 0), 2)

text = f"People: {person_count} | Risk: {risk}"

color = (0,255,0) if risk=="LOW" else (255,255,0) if risk=="MEDIUM" else (255,0,0)

cv2.putText(
    img,
    text,
    (30, 50),
    cv2.FONT_HERSHEY_SIMPLEX,
    1,
    color,
    3
)

plt.figure(figsize=(10,6))
plt.imshow(img)
plt.axis('off')
plt.show()

from google.colab import files
uploaded_video = files.upload()
video_path = list(uploaded_video.keys())[0]
print("Video loaded:", video_path)

import cv2
import matplotlib.pyplot as plt

cap = cv2.VideoCapture(video_path)

counts_over_time = []
frame_idx = 0
display_every = 10

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    frame_idx += 1

    results_v = model(frame)
    boxes_v = results_v[0].boxes.xyxy
    person_count_v = len(boxes_v)

    counts_over_time.append(person_count_v)

    if person_count_v < 15:
        risk_v = "LOW"
        color_v = (0,255,0)
    elif person_count_v < 40:
        risk_v = "MEDIUM"
        color_v = (255,255,0)
    else:
        risk_v = "HIGH"
        color_v = (255,0,0)

    for box in boxes_v:
        x1,y1,x2,y2 = map(int, box)
        cv2.rectangle(frame, (x1,y1), (x2,y2), (255,0,0), 2)

    cv2.putText(
        frame,
        f"People: {person_count_v} | Risk: {risk_v}",
        (30,50),
        cv2.FONT_HERSHEY_SIMPLEX,
        1,
        color_v,
        3
    )

    if frame_idx % display_every == 0:
        plt.figure(figsize=(8,5))
        plt.imshow(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        plt.axis('off')
        plt.show()

cap.release()
print("Video processing complete.")

plt.figure(figsize=(10,4))
plt.plot(counts_over_time)
plt.xlabel("Frame")
plt.ylabel("People Count")
plt.title("Crowd Count Over Time")
plt.grid(True)
plt.show()

import numpy as np

counts = np.array(counts_over_time)

flow = np.diff(counts, prepend=counts[0])

X = np.column_stack((counts, flow))

y = []
for c in counts:
    if c < np.percentile(counts, 33):
        y.append(0)
    elif c < np.percentile(counts, 66):
        y.append(1)
    else:
        y.append(2)

y = np.array(y)

print("Feature shape:", X.shape)
print("Label distribution:", np.unique(y, return_counts=True))

from sklearn.model_selection import train_test_split

Xtr, Xte, ytr, yte = train_test_split(
    X, y,
    test_size=0.2,
    random_state=1,
    stratify=y
)

print("Train labels:", np.unique(ytr, return_counts=True))
print("Test labels:", np.unique(yte, return_counts=True))

from sklearn.model_selection import train_test_split

Xtr, Xte, ytr, yte = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train classes:", np.unique(ytr, return_counts=True))

from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

svm_clf = SVC(kernel='rbf')
svm_clf.fit(Xtr, ytr)

rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(Xtr, ytr)

print("SVM accuracy:", svm_clf.score(Xte, yte))
print("RF accuracy:", rf_clf.score(Xte, yte))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

pred = rf_clf.predict(Xte)
cm = confusion_matrix(yte, pred)

plt.imshow(cm)
plt.colorbar()
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Risk Classification Confusion Matrix")
plt.show()

